# Generated by Django 3.1.2 on 2020-10-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_id', models.IntegerField()),
                ('is_personal_cocktail', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centiliters', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_id', models.IntegerField()),
                ('is_personal_cocktail', models.BooleanField()),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'Awesome'), (5, 'Perfect')], default=5)),
                ('comment', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.CharField(max_length=25)),
                ('recipe', models.TextField()),
                ('ingredients', models.ManyToManyField(through='web_site.CocktailIngredients', to='web_site.IngredientsList')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.user')),
            ],
        ),
        migrations.AddField(
            model_name='cocktailingredients',
            name='cocktail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.personalcocktail'),
        ),
        migrations.AddField(
            model_name='cocktailingredients',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.ingredientslist'),
        ),
        migrations.CreateModel(
            name='BookmarkedCocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_id', models.IntegerField()),
                ('is_personal_cocktail', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.user')),
            ],
        ),
    ]
