# Generated by Django 3.1.2 on 2020-10-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_auto_20201026_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyCocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('cocktail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.personalcocktail')),
            ],
        ),
    ]
