# Generated by Django 3.1.2 on 2020-10-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_auto_20201014_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcocktail',
            name='average',
        ),
        migrations.AddField(
            model_name='personalcocktail',
            name='ingredients',
            field=models.ManyToManyField(through='web_site.CocktailIngredients', to='web_site.IngredientsList'),
        ),
    ]
